'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Kofax.Connector.Text.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A constant text in file name format must have a length less than 128 characters..
        '''</summary>
        Friend ReadOnly Property ERR_CONSTANT_TEXT_MAX_LENGTH() As String
            Get
                Return ResourceManager.GetString("ERR_CONSTANT_TEXT_MAX_LENGTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A file name cannot contain any of following characters: / \ : * ? &quot; &lt; &gt; |.
        '''</summary>
        Friend ReadOnly Property ERR_FILE_NAME_CONTAINS_SPECIAL_CHARS() As String
            Get
                Return ResourceManager.GetString("ERR_FILE_NAME_CONTAINS_SPECIAL_CHARS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A folder path cannot contain any of following characters: /  * ? &quot; &lt; &gt; |.
        '''</summary>
        Friend ReadOnly Property ERR_FOLDER_PATH_CONTAINS_SPECIAL_CHARS() As String
            Get
                Return ResourceManager.GetString("ERR_FOLDER_PATH_CONTAINS_SPECIAL_CHARS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A folder path must have a length less than 254 characters..
        '''</summary>
        Friend ReadOnly Property ERR_FOLDER_PATH_MAX_LENGTH() As String
            Get
                Return ResourceManager.GetString("ERR_FOLDER_PATH_MAX_LENGTH", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property IndexValueButtonImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IndexValueButtonImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Blank Values are not allowed..
        '''</summary>
        Friend ReadOnly Property MSG_BLANK_INDEX_VALUES_NOT_ALLOWED() As String
            Get
                Return ResourceManager.GetString("MSG_BLANK_INDEX_VALUES_NOT_ALLOWED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No default storage folder was specified.
        '''</summary>
        Friend ReadOnly Property MSG_DEFAULT_STORAGE_FOLDER_REQUIRED() As String
            Get
                Return ResourceManager.GetString("MSG_DEFAULT_STORAGE_FOLDER_REQUIRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete all Values?.
        '''</summary>
        Friend ReadOnly Property MSG_DELETE_ALL_VALUES() As String
            Get
                Return ResourceManager.GetString("MSG_DELETE_ALL_VALUES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete this Value?.
        '''</summary>
        Friend ReadOnly Property MSG_DELETE_VALUE() As String
            Get
                Return ResourceManager.GetString("MSG_DELETE_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Index Naming option was selected, but the Index Name field value was not selected..
        '''</summary>
        Friend ReadOnly Property MSG_ERROR_INDEX_NAMING() As String
            Get
                Return ResourceManager.GetString("MSG_ERROR_INDEX_NAMING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No file name was specified.
        '''</summary>
        Friend ReadOnly Property MSG_FILE_NAME_REQUIRED() As String
            Get
                Return ResourceManager.GetString("MSG_FILE_NAME_REQUIRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No image storage folder was specified.
        '''</summary>
        Friend ReadOnly Property MSG_IMAGE_STORAGE_FOFLDER_REQUIRED() As String
            Get
                Return ResourceManager.GetString("MSG_IMAGE_STORAGE_FOFLDER_REQUIRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No index storage folder was specified.
        '''</summary>
        Friend ReadOnly Property MSG_INDEX_STORAGE_FOLDER_REQUIRED() As String
            Get
                Return ResourceManager.GetString("MSG_INDEX_STORAGE_FOLDER_REQUIRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Values have been defined but Index Fields and Batch Fields are available.  Released documents will have no index data available..
        '''</summary>
        Friend ReadOnly Property MSG_NO_INDEX_VALUES() As String
            Get
                Return ResourceManager.GetString("MSG_NO_INDEX_VALUES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The following Batch Fields were not used.{0}.
        '''</summary>
        Friend ReadOnly Property MSG_NOT_ALL_BATCH_FIELDS_USED() As String
            Get
                Return ResourceManager.GetString("MSG_NOT_ALL_BATCH_FIELDS_USED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The following Index Fields were not used.{0}.
        '''</summary>
        Friend ReadOnly Property MSG_NOT_ALL_INDEX_FIELDS_USED() As String
            Get
                Return ResourceManager.GetString("MSG_NOT_ALL_INDEX_FIELDS_USED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No OCR storage folder was specified.
        '''</summary>
        Friend ReadOnly Property MSG_OCR_STORAGE_FOFLDER_REQUIRED() As String
            Get
                Return ResourceManager.GetString("MSG_OCR_STORAGE_FOFLDER_REQUIRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have chosen the &apos;Use Original File Name&apos; option and there are conflicting Text Release script options currently selected. OCR/PDF files must be released to separate directories and/or the standard file naming option must be selected..
        '''</summary>
        Friend ReadOnly Property MSG_ORIGINAL_FILE_NAME_CONFLICT() As String
            Get
                Return ResourceManager.GetString("MSG_ORIGINAL_FILE_NAME_CONFLICT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The PDF 2.01 image format is not supported.
        '''Please run release setup to choose a different image format..
        '''</summary>
        Friend ReadOnly Property MSG_PDF_PUBLISH_FAILED() As String
            Get
                Return ResourceManager.GetString("MSG_PDF_PUBLISH_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No PDF storage folder was specified.
        '''</summary>
        Friend ReadOnly Property MSG_PDF_STORAGE_FOFLDER_REQUIRED() As String
            Get
                Return ResourceManager.GetString("MSG_PDF_STORAGE_FOFLDER_REQUIRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to save the current settings?.
        '''</summary>
        Friend ReadOnly Property MSG_SAVE_SETTING() As String
            Get
                Return ResourceManager.GetString("MSG_SAVE_SETTING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ultimate filename already exists ({0}).
        '''</summary>
        Friend ReadOnly Property MSG_ULTIMATE_FILE_EXISTS() As String
            Get
                Return ResourceManager.GetString("MSG_ULTIMATE_FILE_EXISTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to and More.
        '''</summary>
        Friend ReadOnly Property TXT_AND_MORE() As String
            Get
                Return ResourceManager.GetString("TXT_AND_MORE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ANSI.
        '''</summary>
        Friend ReadOnly Property TXT_ANSI() As String
            Get
                Return ResourceManager.GetString("TXT_ANSI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch class:.
        '''</summary>
        Friend ReadOnly Property TXT_BATCH_CLASS() As String
            Get
                Return ResourceManager.GetString("TXT_BATCH_CLASS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default Storage.
        '''</summary>
        Friend ReadOnly Property TXT_CUSTOM_FOLDER_TITLE_DEFAULT_STORAGE() As String
            Get
                Return ResourceManager.GetString("TXT_CUSTOM_FOLDER_TITLE_DEFAULT_STORAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image Ouput.
        '''</summary>
        Friend ReadOnly Property TXT_CUSTOM_FOLDER_TITLE_IMAGE_STORAGE() As String
            Get
                Return ResourceManager.GetString("TXT_CUSTOM_FOLDER_TITLE_IMAGE_STORAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Index Storage.
        '''</summary>
        Friend ReadOnly Property TXT_CUSTOM_FOLDER_TITLE_INDEX_STORAGE() As String
            Get
                Return ResourceManager.GetString("TXT_CUSTOM_FOLDER_TITLE_INDEX_STORAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OCR Output.
        '''</summary>
        Friend ReadOnly Property TXT_CUSTOM_FOLDER_TITLE_OCR_STORAGE() As String
            Get
                Return ResourceManager.GetString("TXT_CUSTOM_FOLDER_TITLE_OCR_STORAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF Output.
        '''</summary>
        Friend ReadOnly Property TXT_CUSTOM_FOLDER_TITLE_PDF_STORAGE() As String
            Get
                Return ResourceManager.GetString("TXT_CUSTOM_FOLDER_TITLE_PDF_STORAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Verification Failed: .
        '''</summary>
        Friend ReadOnly Property TXT_DATA_VERIFICATION_FAILED() As String
            Get
                Return ResourceManager.GetString("TXT_DATA_VERIFICATION_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Verification Information: .
        '''</summary>
        Friend ReadOnly Property TXT_DATA_VERIFY_INFOMATION() As String
            Get
                Return ResourceManager.GetString("TXT_DATA_VERIFY_INFOMATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document class:.
        '''</summary>
        Friend ReadOnly Property TXT_DOCUMENT_CLASS() As String
            Get
                Return ResourceManager.GetString("TXT_DOCUMENT_CLASS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export.
        '''</summary>
        Friend ReadOnly Property TXT_EXPORT_FOLDER() As String
            Get
                Return ResourceManager.GetString("TXT_EXPORT_FOLDER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend ReadOnly Property TXT_LocalizedValueTrue() As String
            Get
                Return ResourceManager.GetString("TXT_LocalizedValueTrue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch Class Name.
        '''</summary>
        Friend ReadOnly Property TXT_MACRO_BATCHCLASSNAME() As String
            Get
                Return ResourceManager.GetString("TXT_MACRO_BATCHCLASSNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document Class Name.
        '''</summary>
        Friend ReadOnly Property TXT_MACRO_DOCCLASSNAME() As String
            Get
                Return ResourceManager.GetString("TXT_MACRO_DOCCLASSNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document ID.
        '''</summary>
        Friend ReadOnly Property TXT_MACRO_DOCID() As String
            Get
                Return ResourceManager.GetString("TXT_MACRO_DOCID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Name:.
        '''</summary>
        Friend ReadOnly Property TXT_NAME() As String
            Get
                Return ResourceManager.GetString("TXT_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text Export Connector Error.
        '''</summary>
        Friend ReadOnly Property TXT_RELEASE_ERROR() As String
            Get
                Return ResourceManager.GetString("TXT_RELEASE_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text Export Connector Setup Error.
        '''</summary>
        Friend ReadOnly Property TXT_RELEASE_SETUP_ERROR() As String
            Get
                Return ResourceManager.GetString("TXT_RELEASE_SETUP_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Settings.
        '''</summary>
        Friend ReadOnly Property TXT_SAVE_SETTING() As String
            Get
                Return ResourceManager.GetString("TXT_SAVE_SETTING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sequence.
        '''</summary>
        Friend ReadOnly Property TXT_SEQUENCE() As String
            Get
                Return ResourceManager.GetString("TXT_SEQUENCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text Export Connector.
        '''</summary>
        Friend ReadOnly Property TXT_SHORT_PRODUCT_NAME() As String
            Get
                Return ResourceManager.GetString("TXT_SHORT_PRODUCT_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UTF16.
        '''</summary>
        Friend ReadOnly Property TXT_UTF16() As String
            Get
                Return ResourceManager.GetString("TXT_UTF16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UTF8.
        '''</summary>
        Friend ReadOnly Property TXT_UTF8() As String
            Get
                Return ResourceManager.GetString("TXT_UTF8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value.
        '''</summary>
        Friend ReadOnly Property TXT_VALUE() As String
            Get
                Return ResourceManager.GetString("TXT_VALUE", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
